// Copyright 2018 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: filter.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Op is the operation to apply.
type Predicate_Op int32

const (
	Predicate_UNKNOWN Predicate_Op = 0
	// Operators on scalar values. Only applies to one of |int_value|,
	// |long_value|, |string_value| or |timestamp_value|.
	Predicate_EQUALS              Predicate_Op = 1
	Predicate_NOT_EQUALS          Predicate_Op = 2
	Predicate_GREATER_THAN        Predicate_Op = 3
	Predicate_GREATER_THAN_EQUALS Predicate_Op = 5
	Predicate_LESS_THAN           Predicate_Op = 6
	Predicate_LESS_THAN_EQUALS    Predicate_Op = 7
	// Checks if the value is a member of a given array, which should be one of
	// |int_values|, |long_values| or |string_values|.
	Predicate_IN Predicate_Op = 8
)

var Predicate_Op_name = map[int32]string{
	0: "UNKNOWN",
	1: "EQUALS",
	2: "NOT_EQUALS",
	3: "GREATER_THAN",
	5: "GREATER_THAN_EQUALS",
	6: "LESS_THAN",
	7: "LESS_THAN_EQUALS",
	8: "IN",
}

var Predicate_Op_value = map[string]int32{
	"UNKNOWN":             0,
	"EQUALS":              1,
	"NOT_EQUALS":          2,
	"GREATER_THAN":        3,
	"GREATER_THAN_EQUALS": 5,
	"LESS_THAN":           6,
	"LESS_THAN_EQUALS":    7,
	"IN":                  8,
}

func (x Predicate_Op) String() string {
	return proto.EnumName(Predicate_Op_name, int32(x))
}

func (Predicate_Op) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1f5303cab7a20d6f, []int{0, 0}
}

// Predicate captures individual conditions that must be true for a resource
// being filtered.
type Predicate struct {
	Op  Predicate_Op `protobuf:"varint,1,opt,name=op,proto3,enum=api.Predicate_Op" json:"op,omitempty"`
	Key string       `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// Types that are valid to be assigned to Value:
	//	*Predicate_IntValue
	//	*Predicate_LongValue
	//	*Predicate_StringValue
	//	*Predicate_TimestampValue
	//	*Predicate_IntValues
	//	*Predicate_LongValues
	//	*Predicate_StringValues
	Value                isPredicate_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Predicate) Reset()         { *m = Predicate{} }
func (m *Predicate) String() string { return proto.CompactTextString(m) }
func (*Predicate) ProtoMessage()    {}
func (*Predicate) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f5303cab7a20d6f, []int{0}
}

func (m *Predicate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Predicate.Unmarshal(m, b)
}
func (m *Predicate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Predicate.Marshal(b, m, deterministic)
}
func (m *Predicate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Predicate.Merge(m, src)
}
func (m *Predicate) XXX_Size() int {
	return xxx_messageInfo_Predicate.Size(m)
}
func (m *Predicate) XXX_DiscardUnknown() {
	xxx_messageInfo_Predicate.DiscardUnknown(m)
}

var xxx_messageInfo_Predicate proto.InternalMessageInfo

func (m *Predicate) GetOp() Predicate_Op {
	if m != nil {
		return m.Op
	}
	return Predicate_UNKNOWN
}

func (m *Predicate) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type isPredicate_Value interface {
	isPredicate_Value()
}

type Predicate_IntValue struct {
	IntValue int32 `protobuf:"varint,3,opt,name=int_value,json=intValue,proto3,oneof"`
}

type Predicate_LongValue struct {
	LongValue int64 `protobuf:"varint,4,opt,name=long_value,json=longValue,proto3,oneof"`
}

type Predicate_StringValue struct {
	StringValue string `protobuf:"bytes,5,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Predicate_TimestampValue struct {
	TimestampValue *timestamp.Timestamp `protobuf:"bytes,6,opt,name=timestamp_value,json=timestampValue,proto3,oneof"`
}

type Predicate_IntValues struct {
	IntValues *IntValues `protobuf:"bytes,7,opt,name=int_values,json=intValues,proto3,oneof"`
}

type Predicate_LongValues struct {
	LongValues *LongValues `protobuf:"bytes,8,opt,name=long_values,json=longValues,proto3,oneof"`
}

type Predicate_StringValues struct {
	StringValues *StringValues `protobuf:"bytes,9,opt,name=string_values,json=stringValues,proto3,oneof"`
}

func (*Predicate_IntValue) isPredicate_Value() {}

func (*Predicate_LongValue) isPredicate_Value() {}

func (*Predicate_StringValue) isPredicate_Value() {}

func (*Predicate_TimestampValue) isPredicate_Value() {}

func (*Predicate_IntValues) isPredicate_Value() {}

func (*Predicate_LongValues) isPredicate_Value() {}

func (*Predicate_StringValues) isPredicate_Value() {}

func (m *Predicate) GetValue() isPredicate_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Predicate) GetIntValue() int32 {
	if x, ok := m.GetValue().(*Predicate_IntValue); ok {
		return x.IntValue
	}
	return 0
}

func (m *Predicate) GetLongValue() int64 {
	if x, ok := m.GetValue().(*Predicate_LongValue); ok {
		return x.LongValue
	}
	return 0
}

func (m *Predicate) GetStringValue() string {
	if x, ok := m.GetValue().(*Predicate_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (m *Predicate) GetTimestampValue() *timestamp.Timestamp {
	if x, ok := m.GetValue().(*Predicate_TimestampValue); ok {
		return x.TimestampValue
	}
	return nil
}

func (m *Predicate) GetIntValues() *IntValues {
	if x, ok := m.GetValue().(*Predicate_IntValues); ok {
		return x.IntValues
	}
	return nil
}

func (m *Predicate) GetLongValues() *LongValues {
	if x, ok := m.GetValue().(*Predicate_LongValues); ok {
		return x.LongValues
	}
	return nil
}

func (m *Predicate) GetStringValues() *StringValues {
	if x, ok := m.GetValue().(*Predicate_StringValues); ok {
		return x.StringValues
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Predicate) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Predicate_OneofMarshaler, _Predicate_OneofUnmarshaler, _Predicate_OneofSizer, []interface{}{
		(*Predicate_IntValue)(nil),
		(*Predicate_LongValue)(nil),
		(*Predicate_StringValue)(nil),
		(*Predicate_TimestampValue)(nil),
		(*Predicate_IntValues)(nil),
		(*Predicate_LongValues)(nil),
		(*Predicate_StringValues)(nil),
	}
}

func _Predicate_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Predicate)
	// value
	switch x := m.Value.(type) {
	case *Predicate_IntValue:
		b.EncodeVarint(3<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.IntValue))
	case *Predicate_LongValue:
		b.EncodeVarint(4<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.LongValue))
	case *Predicate_StringValue:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.StringValue)
	case *Predicate_TimestampValue:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.TimestampValue); err != nil {
			return err
		}
	case *Predicate_IntValues:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.IntValues); err != nil {
			return err
		}
	case *Predicate_LongValues:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.LongValues); err != nil {
			return err
		}
	case *Predicate_StringValues:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.StringValues); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Predicate.Value has unexpected type %T", x)
	}
	return nil
}

func _Predicate_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Predicate)
	switch tag {
	case 3: // value.int_value
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &Predicate_IntValue{int32(x)}
		return true, err
	case 4: // value.long_value
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &Predicate_LongValue{int64(x)}
		return true, err
	case 5: // value.string_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Value = &Predicate_StringValue{x}
		return true, err
	case 6: // value.timestamp_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(timestamp.Timestamp)
		err := b.DecodeMessage(msg)
		m.Value = &Predicate_TimestampValue{msg}
		return true, err
	case 7: // value.int_values
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(IntValues)
		err := b.DecodeMessage(msg)
		m.Value = &Predicate_IntValues{msg}
		return true, err
	case 8: // value.long_values
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(LongValues)
		err := b.DecodeMessage(msg)
		m.Value = &Predicate_LongValues{msg}
		return true, err
	case 9: // value.string_values
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(StringValues)
		err := b.DecodeMessage(msg)
		m.Value = &Predicate_StringValues{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Predicate_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Predicate)
	// value
	switch x := m.Value.(type) {
	case *Predicate_IntValue:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.IntValue))
	case *Predicate_LongValue:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.LongValue))
	case *Predicate_StringValue:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.StringValue)))
		n += len(x.StringValue)
	case *Predicate_TimestampValue:
		s := proto.Size(x.TimestampValue)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Predicate_IntValues:
		s := proto.Size(x.IntValues)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Predicate_LongValues:
		s := proto.Size(x.LongValues)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Predicate_StringValues:
		s := proto.Size(x.StringValues)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type IntValues struct {
	Value                []int32  `protobuf:"varint,1,rep,packed,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IntValues) Reset()         { *m = IntValues{} }
func (m *IntValues) String() string { return proto.CompactTextString(m) }
func (*IntValues) ProtoMessage()    {}
func (*IntValues) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f5303cab7a20d6f, []int{1}
}

func (m *IntValues) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntValues.Unmarshal(m, b)
}
func (m *IntValues) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntValues.Marshal(b, m, deterministic)
}
func (m *IntValues) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntValues.Merge(m, src)
}
func (m *IntValues) XXX_Size() int {
	return xxx_messageInfo_IntValues.Size(m)
}
func (m *IntValues) XXX_DiscardUnknown() {
	xxx_messageInfo_IntValues.DiscardUnknown(m)
}

var xxx_messageInfo_IntValues proto.InternalMessageInfo

func (m *IntValues) GetValue() []int32 {
	if m != nil {
		return m.Value
	}
	return nil
}

type StringValues struct {
	Values               []string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringValues) Reset()         { *m = StringValues{} }
func (m *StringValues) String() string { return proto.CompactTextString(m) }
func (*StringValues) ProtoMessage()    {}
func (*StringValues) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f5303cab7a20d6f, []int{2}
}

func (m *StringValues) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringValues.Unmarshal(m, b)
}
func (m *StringValues) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringValues.Marshal(b, m, deterministic)
}
func (m *StringValues) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringValues.Merge(m, src)
}
func (m *StringValues) XXX_Size() int {
	return xxx_messageInfo_StringValues.Size(m)
}
func (m *StringValues) XXX_DiscardUnknown() {
	xxx_messageInfo_StringValues.DiscardUnknown(m)
}

var xxx_messageInfo_StringValues proto.InternalMessageInfo

func (m *StringValues) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

type LongValues struct {
	Values               []int64  `protobuf:"varint,3,rep,packed,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LongValues) Reset()         { *m = LongValues{} }
func (m *LongValues) String() string { return proto.CompactTextString(m) }
func (*LongValues) ProtoMessage()    {}
func (*LongValues) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f5303cab7a20d6f, []int{3}
}

func (m *LongValues) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LongValues.Unmarshal(m, b)
}
func (m *LongValues) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LongValues.Marshal(b, m, deterministic)
}
func (m *LongValues) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LongValues.Merge(m, src)
}
func (m *LongValues) XXX_Size() int {
	return xxx_messageInfo_LongValues.Size(m)
}
func (m *LongValues) XXX_DiscardUnknown() {
	xxx_messageInfo_LongValues.DiscardUnknown(m)
}

var xxx_messageInfo_LongValues proto.InternalMessageInfo

func (m *LongValues) GetValues() []int64 {
	if m != nil {
		return m.Values
	}
	return nil
}

// Filter is used to filter resources returned from a ListXXX request.
type Filter struct {
	// All predicates are AND-ed when this filter is applied.
	Predicate            []*Predicate `protobuf:"bytes,1,rep,name=predicate,proto3" json:"predicate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Filter) Reset()         { *m = Filter{} }
func (m *Filter) String() string { return proto.CompactTextString(m) }
func (*Filter) ProtoMessage()    {}
func (*Filter) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f5303cab7a20d6f, []int{4}
}

func (m *Filter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Filter.Unmarshal(m, b)
}
func (m *Filter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Filter.Marshal(b, m, deterministic)
}
func (m *Filter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Filter.Merge(m, src)
}
func (m *Filter) XXX_Size() int {
	return xxx_messageInfo_Filter.Size(m)
}
func (m *Filter) XXX_DiscardUnknown() {
	xxx_messageInfo_Filter.DiscardUnknown(m)
}

var xxx_messageInfo_Filter proto.InternalMessageInfo

func (m *Filter) GetPredicate() []*Predicate {
	if m != nil {
		return m.Predicate
	}
	return nil
}

func init() {
	proto.RegisterEnum("api.Predicate_Op", Predicate_Op_name, Predicate_Op_value)
	proto.RegisterType((*Predicate)(nil), "api.Predicate")
	proto.RegisterType((*IntValues)(nil), "api.IntValues")
	proto.RegisterType((*StringValues)(nil), "api.StringValues")
	proto.RegisterType((*LongValues)(nil), "api.LongValues")
	proto.RegisterType((*Filter)(nil), "api.Filter")
}

func init() { proto.RegisterFile("filter.proto", fileDescriptor_1f5303cab7a20d6f) }

var fileDescriptor_1f5303cab7a20d6f = []byte{
	// 449 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x92, 0xd1, 0x6e, 0xd3, 0x30,
	0x18, 0x85, 0xe3, 0x78, 0x49, 0xeb, 0xbf, 0x59, 0x17, 0x7e, 0x26, 0x88, 0x26, 0xa1, 0x65, 0x05,
	0xa1, 0x5c, 0xa0, 0x54, 0x2a, 0x12, 0xe2, 0xb6, 0x48, 0x81, 0x4c, 0x54, 0x29, 0xb8, 0x1d, 0x5c,
	0x56, 0x19, 0x64, 0x55, 0x44, 0xd7, 0x58, 0x75, 0x8a, 0xc4, 0x03, 0xf0, 0x16, 0x3c, 0x2c, 0x8a,
	0x13, 0xbb, 0xb9, 0x8b, 0x8f, 0xbf, 0xe3, 0x9c, 0x63, 0xff, 0xe0, 0x3d, 0x94, 0xbb, 0xba, 0x38,
	0xc4, 0xe2, 0x50, 0xd5, 0x15, 0xd2, 0x5c, 0x94, 0x57, 0xd7, 0xdb, 0xaa, 0xda, 0xee, 0x8a, 0xa9,
	0x92, 0xee, 0x8f, 0x0f, 0xd3, 0xba, 0x7c, 0x2c, 0x64, 0x9d, 0x3f, 0x8a, 0x96, 0x9a, 0xfc, 0x3b,
	0x03, 0xf6, 0xe5, 0x50, 0xfc, 0x2c, 0x7f, 0xe4, 0x75, 0x81, 0x37, 0x60, 0x57, 0x22, 0x20, 0x21,
	0x89, 0xc6, 0xb3, 0x27, 0x71, 0x2e, 0xca, 0xd8, 0xec, 0xc5, 0x4b, 0xc1, 0xed, 0x4a, 0xa0, 0x0f,
	0xf4, 0x57, 0xf1, 0x27, 0xb0, 0x43, 0x12, 0x31, 0xde, 0x7c, 0xe2, 0x0b, 0x60, 0xe5, 0xbe, 0xde,
	0xfc, 0xce, 0x77, 0xc7, 0x22, 0xa0, 0x21, 0x89, 0x9c, 0xd4, 0xe2, 0xc3, 0x72, 0x5f, 0x7f, 0x6b,
	0x14, 0xbc, 0x06, 0xd8, 0x55, 0xfb, 0x6d, 0xb7, 0x7f, 0x16, 0x92, 0x88, 0xa6, 0x16, 0x67, 0x8d,
	0xd6, 0x02, 0x2f, 0xc1, 0x93, 0xf5, 0xa1, 0x34, 0x88, 0xd3, 0x1c, 0x9d, 0x5a, 0x7c, 0xd4, 0xaa,
	0x2d, 0x94, 0xc0, 0x85, 0x89, 0xde, 0x71, 0x6e, 0x48, 0xa2, 0xd1, 0xec, 0x2a, 0x6e, 0x2b, 0xc6,
	0xba, 0x62, 0xbc, 0xd6, 0x5c, 0x6a, 0xf1, 0xb1, 0x31, 0xb5, 0xc7, 0x4c, 0x01, 0x4c, 0x56, 0x19,
	0x0c, 0xd4, 0x09, 0x63, 0x55, 0xf4, 0xb6, 0xcb, 0x2b, 0x9b, 0x70, 0x3a, 0xbc, 0xc4, 0x19, 0x8c,
	0x4e, 0xe9, 0x65, 0x30, 0x54, 0x8e, 0x0b, 0xe5, 0x58, 0xe8, 0x06, 0x8d, 0x05, 0x4c, 0x1f, 0x89,
	0xef, 0xe1, 0xbc, 0x5f, 0x48, 0x06, 0x4c, 0xb9, 0xda, 0x0b, 0x5d, 0x9d, 0x4a, 0x35, 0x3e, 0xaf,
	0x57, 0x52, 0x4e, 0xfe, 0x12, 0xb0, 0x97, 0x02, 0x47, 0x30, 0xb8, 0xcb, 0x3e, 0x67, 0xcb, 0xef,
	0x99, 0x6f, 0x21, 0x80, 0x9b, 0x7c, 0xbd, 0x9b, 0x2f, 0x56, 0x3e, 0xc1, 0x31, 0x40, 0xb6, 0x5c,
	0x6f, 0xba, 0xb5, 0x8d, 0x3e, 0x78, 0x9f, 0x78, 0x32, 0x5f, 0x27, 0x7c, 0xb3, 0x4e, 0xe7, 0x99,
	0x4f, 0xf1, 0x39, 0x3c, 0xed, 0x2b, 0x1a, 0x75, 0xf0, 0x1c, 0xd8, 0x22, 0x59, 0xad, 0x5a, 0xce,
	0xc5, 0x4b, 0xf0, 0xcd, 0x52, 0x43, 0x03, 0x74, 0xc1, 0xbe, 0xcd, 0xfc, 0xe1, 0x87, 0x01, 0x38,
	0x2a, 0xfa, 0xe4, 0x06, 0x98, 0xb9, 0x18, 0xbc, 0xec, 0xd4, 0x80, 0x84, 0x34, 0x72, 0x78, 0x87,
	0xbc, 0x06, 0xaf, 0xdf, 0x09, 0x9f, 0x81, 0xdb, 0xd5, 0xb6, 0x43, 0x1a, 0x31, 0xde, 0xad, 0x26,
	0xaf, 0x00, 0x4e, 0x37, 0xd6, 0xa3, 0x68, 0x48, 0x23, 0x6a, 0xa8, 0x77, 0xe0, 0x7e, 0x54, 0x53,
	0x8c, 0x6f, 0x80, 0x09, 0x3d, 0x7c, 0xea, 0x8f, 0xfa, 0xa5, 0xcc, 0x48, 0xf2, 0x13, 0x70, 0xef,
	0xaa, 0xe7, 0x7f, 0xfb, 0x3f, 0x00, 0x00, 0xff, 0xff, 0x6c, 0x05, 0x68, 0x03, 0x04, 0x03, 0x00,
	0x00,
}
