// Copyright 2018 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by go-swagger; DO NOT EDIT.

package run_model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// APIFilter Filter is used to filter resources returned from a ListXXX request.
// swagger:model apiFilter
type APIFilter struct {

	// All predicates are AND-ed when this filter is applied.
	Predicate []*APIPredicate `json:"predicate"`
}

// Validate validates this api filter
func (m *APIFilter) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePredicate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIFilter) validatePredicate(formats strfmt.Registry) error {

	if swag.IsZero(m.Predicate) { // not required
		return nil
	}

	for i := 0; i < len(m.Predicate); i++ {
		if swag.IsZero(m.Predicate[i]) { // not required
			continue
		}

		if m.Predicate[i] != nil {
			if err := m.Predicate[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("predicate" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *APIFilter) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIFilter) UnmarshalBinary(b []byte) error {
	var res APIFilter
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
